# Generated by Django 5.0.3 on 2024-04-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_article_view_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
