# Generated by Django 5.0.3 on 2024-04-26 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='номер версии')),
                ('name', models.CharField(max_length=50, verbose_name='название версии')),
                ('is_active', models.BooleanField(default=True, verbose_name='признак активности версии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.product', verbose_name='ID продукта')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
            },
        ),
    ]
