# Generated by Django 4.2.2 on 2024-05-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price',), 'permissions': [('set_published_status', 'Can publish product'), ('edit_product_description', 'Can edit product description'), ('edit_product_category', 'Can edit product category')], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
